GET http://localhost:3000/notes
Content-Type: application/json

####

GET http://localhost:3000/notes/67a3eec9265fd9a6d1160d86
Content-Type: application/json

####
POST http://localhost:3000/notes
Content-Type: application/json
{
  "title": "Note 2",
  "content": "This is my second note"
}

####

PUT http://localhost:3000/notes/67a3eec9265fd9a6d1160d86
Content-Type: application/json

{
  "title": "Updated Note 1",
  "content": "This is the updated content for my first note"
}

####

DELETE http://localhost:3000/notes/67a3eec9265fd9a6d1160d86
Content-Type: application/json

####

DELETE http://localhost:3000/notes
Content-Type: application/json
