POST  http://localhost:5000/register
Content-Type: application/json

{
  "username": "joe_404",
  "email": "joe@example.com",
  "password": "securepass"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "joe@example.com",
  "password": "securepass"
}

###

GET http://localhost:5000/dashboard 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTNlMTFjYWYwODI1NTZhZTE0OTU3MyIsImlhdCI6MTczODc5NTA0NiwiZXhwIjoxNzM4Nzk4NjQ2fQ.GsLpkCUGHQUl9anY9425pwIGmueHobOmkjcW1rvJRk0
Content-Type: application/json
